# Generated by Django 3.1.7 on 2021-05-25 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='user_email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
